# Site settings
title: Actio1680, proyectos en Derecho e Inform√°tica
tag_text: Actio1680, un sitio web de William Atencio Becerra
description: 

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
